codeit-team3/FE

src/app/layout.tsx
> #13 
> 전역적으로 배경 색상, padding 설정했습니다.
=> 💄[Design] 전역 배경 색상 및 패딩 설정 #13

.github/workflows/ci-develop.yml, .github/workflows/main-deploy.yml
> #24
> Develop, main 브랜치 push, pr올라올시 ci 작업테스트 후 성공-> 웹훅 연결되도록 지정
이런식으로 deveop, main 브랜치에 pr생성, push 되는 경우 -> 각 파일의 ci 작업을 우선 테스트 -> 성공시 디스코드에 알림 
저 상단의 파란색 title 누르면 해당 Pr로 이동합니다.
* 혹시 적용 이후 알림이 너무 빈번하거나 알림 조건을 수정하면 좋을 것 같다는 의견 있으시면 언제든지 주면 좋을 것 같아요!
=> 📦[Chore] discord webhook 연결

src/components/progress-bar/ProgressBar.stories.tsx, src/components/progress-bar/ProgressBar.test.tsx, src/components/progress-bar/ProgressBar.tsx
> ex) #16 , #17 
> 현재인원 / 정원을 표시하는 프로그레스바 개발
* 스토리북 빌드 링크 : https://6746699afaee05c7e6fef863-enpzuapmsc.chromatic.com/?path=/story/components-progressbar--default
* `Default`는  기본 피그마 구현대로 사이즈를 지정하고 border-radius, height를 선택적으로 받아 커스텀할 수 있습니다
* 정원이 가득차면 색이 살짝 변경됩니다
* 렌더할 때 상위 div아래에 `width`를 지정하고 사용하면 해당 div너비만큼 늘어나도록 설정했습니다.
=> ✨ [Feature] progressBar 컴포넌트 개발

src/app/layout.tsx
> ex) #64 
> Rootlayout padding 추가
navbar만큼 임시로 rootlayout에 padding을 적용해서 children 페이지들과 겹치지 않도록 했습니다.
* 작업을 위한 임시방편 코드라 나중에 좀 더 리팩토링이 필요합니다!
=> 💄[Design] rootlayout 상단 padding 추가

src/components/drop-down/DropDown.tsx, src/components/drop-down/DroptDown.stories.tsx
#47 
> ex) #이슈번호, #이슈번호
> 이번 PR에서 작업한 내용을 간략히 설명해주세요
드롭다운 컴포넌트의 variant와 size를 옵션으로 설정할 수 있게 스토리북 테스트코드 구현
=> ✅[Test] 드롭다운 컴포넌트 storybook test코드 작성

.github/workflows/chromatic.yml, .github/workflows/ci.yml
> ex) #52 
> 📦 ci 작업 범위를 기존 Develop에서 모든 브랜치의 pr로 수정하고 그에 따라 알림 메시지 수정
* 수정은 해뒀는데 사용해보면서 실제로 어떻게 동작하는지 확인이 필요할 것 같습니다... 확인해보고 수정할 부분 이후 수정하도록 하겠습니다!
=> 📦[Chore] ci 작업 범위 및 메시지 수정

.gitattributes
#70
- .gitattributes 파일을 루트에 추가하고 .ts, .tsx 파일의 줄 바꿈을 LF로 통일하는 설정 추가
Window에서 작업한 사용자가 checkout시 LF 줄바꿈을 CRLF로 변환하고, 변경사항 커밋시 LF로 줄바꿈이 되도록 설정됩니다.
CRLF와 LF와 관련된 개념은 연관 이슈에 정리했습니다. 
참고부탁드립니다!
=> 📦[Chore] 줄 바꿈 스타일(LF) 통일 .gitattributes 파일 추가 #70

next.config.ts, src/components/avatar-group/AvatarGroup.stories.tsx, src/components/avatar-group/AvatarGroup.test.tsx, src/components/avatar-group/AvatarGroup.tsx, src/components/avatar/Avatar.stories.tsx, src/components/avatar/Avatar.test.tsx, src/components/avatar/Avatar.tsx, src/constants/avatar.ts, src/constants/index.ts
> ex) #66 ,
> avatar, avatarGroup 컴포넌트 구현
* avatar랑 avatar-group을 묶어서 같이 보는게 좋을 것 같아서 하나의 이슈로 생성했는데, 실수로 테스트 코드 작업이랑 스토리북 작업을 분리를 못했습니다... 죄송합니다 ㅠㅠ
* 추가로 코드량이 많지 않은 경우는 기존처럼 tsx, test, storybook 코드를 한 pr로 봐도 괜찮을 것 같다는 생각이 들어서 추후에 얘기나눠보면 좋을 것 같아요 (작업해보니 앞으로 하게될 페이지 단위 작업이나 여러 컴포넌트들을 합친 컴포넌트의 경우는 파일이 비대해지기 때문에 이런 작업들은 테스트 코드 작업을 분리하면 좋겠지만 작은 컴포넌트는 나누는게 오히려 번거로울 것 같다는 생각이 들었습니다!)
* 아마 avtar-group 같은 경우 제가 작업하는 모임 상세페이지 제외하고 쓸 일이 없을 것 같긴한데 기본 avatar의 경우는 다른 분들도 프로필 이미지 넣을 때 활용하시면 좋을 것 같습니다!
* 우선 피그마 보고 사용되는 사이즈 3개로 확인해서 `constants` 폴더에 사이즈 기입해두었는데 개발하시다가 추가하셔야 되면 이쪽에 사이즈 추가하면 될 것 같습니다!
=> ✨[Feat] Avatar, AvatarGroup 컴포넌트 구현

src/app/login/page.tsx, src/features/auth/container/login-form/LoginForm.test.tsx, src/features/auth/container/login-form/LoginForm.tsx, src/middleware.ts
> #34 #43 
> ### 인증 미들웨어 구현 작업
Next.js 미들웨어를 활용하여 페이지 접근 권한 관리 시스템을 구현했습니다.
1. 인증이 필요한 보호된 경로(예시 -> `/exchange`, `/wish`, `/profile`)에 대한 접근 제어
2. 비인증 사용자의 보호된 경로 접근 시 로그인 페이지로 자동 리디렉션
3. 로그인 완료 후 원래 접근하려던 페이지로 복귀하기 위한 `returnUrl` 파라미터 처리
4. 이미 인증된 사용자의 로그인 페이지 접근 시 메인 페이지로 리디렉션
https://github.com/user-attachments/assets/aa7329ca-fa04-488a-9881-4ff780b3e931
=> ✨[Feat] 페이지별 권한에 따른 접근 처리 기능 구현 #43

src/features/auth/container/login-form/LoginForm.stories.tsx
=> 🐛[Fix] LoginForm storybook 에러 해결

src/app/login/page.tsx, src/features/auth/container/login-form/LoginForm.tsx
=> 💄[Design] 반응형 디자인 수정 #173

src/features/bookclub/components/ClubListSection.tsx, src/features/bookclub/components/HeaderSection.tsx
> #180
> 모임 메이페이지 이동 로직 추가
- 생성하기 버튼 클릭시 생성하기 페이지로 이동
- 카드 클릭시 모임 상세 페이지로 이동
체크 필터에서 사용하고 있는 `IcCheck` 내부 로직이 달라져서 기존 모양이랑 달라진 것 같아요!
`IcCheck` 사용 불가시 체크박스 체크 모양만 svg로 가져와서 따로 적용시켜야 할 것 같습니다!
=> ✨[Feat] 모임 메이페이지 이동 로직 추가 #180

src/features/bookclub/components/FilterSection.tsx, src/features/club-details/components/HeaderSection.tsx, src/features/profile/container/ClubContents.tsx, src/features/profile/container/MainContent.tsx, src/features/profile/container/ProfilePage.tsx, src/middleware.ts
> #183
> 서비스 전반 리팩토링 
- 마이페이지 스크롤 이슈
- 모임 찾기 페이지 필터섹션 드롭다운 스크롤 이슈
- 미들웨어 인증 필요 페이지 추가
=> ♻️[Refactor] refactor 서비스 전반 코드 리팩토링

src/components/badge/Badge.stories.tsx, src/components/badge/Badge.test.tsx, src/components/badge/Badge.tsx
> ex) #208, #207 
> 뱃지 컴포넌트 개발 및 테스트
props로 `count` , `size`, `variant` 값을 받습니다.
`size`의 경우 기본 md (26x26)으로 설정되어있습니다.
999가 넘을 경우 +처리
`variant`의 경우 나중에 알림표시등을 위해 `dot` 을 추가해두긴 했는데 현재 디자인상으로는 사용안해도 무관한 값입니다.
추후에 위치 정보값 (`vertical` 등)에 따라 뱃지로 감싸는 컴포넌트의 어느 위치에 사용될지의 기능이 추가될 수 있을 것 같습니다.
=> ✨ [Feat] 뱃지 컴포넌트 구현

src/components/chat-card/ChatCard.test.tsx, src/components/chat-card/ChatCard.tsx
> ex) #215, #206
> 채팅 카드 컴포넌트 테스트 코드 작성
> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요
브랜치 나누고 작업하다가 실수로 해당 pr (https://github.com/codeit-team3/FE/pull/214) 이 닫혀버렸습니다... 
제가 child브랜치 작업 내용을 가져오는 과정에서 머지를 실수한 것 같은데, 이미 머지되었다고 pr 재오픈이 안되네요 ㅠㅠ
**해당 pr은 위에서 말씀드린 실수로 닫힌 pr이 머지된 이후, 테스트 코드만 작성한 내용이라 닫힌 pr 내용 한 번 읽어주신 후에 해당 pr 리뷰해주시면 감사하겠습니다 ㅠㅠ**
닫힌 pr(https://github.com/codeit-team3/FE/pull/214) 도 읽고 코멘트 달아주시면 추후 상위 브랜치에서 수정해서 develop에 올리도록 하겠습니다!
=> ✅ [Test] 채팅 카드 컴포넌트 테스트 코드 작성

package-lock.json, package.json, src/app/actions.ts, src/app/layout.tsx, src/components/toast/toast.tsx, src/features/auth/api/auth.ts, src/features/auth/hooks/useLoginSubmit.ts, src/lib/utils/apiClient.ts, src/middleware.ts
> #188 
> 
access token이 만료 되었을 때 1. 비로그인 상태에서 접근 제한 되어 있는 페이지 접근, 2. 인증이 필요한 api 호출을 하게 되었을 때 access token 재발급 받아서 재인증 되도록 구현했습니다.
인증쪽은 중요한 부분이라고 생각하여 이후에도 계속 찾아보면서 리펙토링 해야할 것 같습니다.
=> ✨[Feat] accessToken 만료 되었을 때  refresh #188

package-lock.json
> ex) #221 , #이슈번호
> msw 설치 후 npm install시 경고 문구 해결을 위한 패키지 재설치
develop에서 npm install시 사진과 같은 경고문구가 뜨는 것 같습니다.
ai한테 물어보니 아래와 같이 답변해줘서 우선 재설치하고 경고문구 안뜨는것만 확인했습니다.
=> 🐛 [Bug] msw 적용 후 Npm install시 보안 경고

src/app/layout.tsx
> ex) #225, #이슈번호
>레이아웃 수정
아마 병합문제로 children이 2개가 되어버려서 하나 삭제했습니다!
=> 🐛 [Fix] 레이아웃 수정

src/components/avatar/Avatar.tsx, src/components/chat-container/chat-bubble/ChatBubble.stories.tsx, src/components/chat-container/chat-bubble/ChatBubble.test.tsx, src/components/chat-container/chat-bubble/ChatBubble.tsx, src/components/chat-container/chat-bubble/VariantChatBubble.stories.tsx, src/components/chat-container/chat-bubble/types/chatBubble.ts, src/components/chat-container/chat-bubble/types/index.ts, src/components/chat-container/chat-bubble/types/variantChatBubble.ts, src/constants/avatar.ts
> ex) #224, #223 
> 채팅 페이지에서 사용되는 말풍선 컴포넌트를 구현했습니다.
variant는 총 3개로 구현되어 있습니다. (`ME`, `OPPONENT`, `SYSTEM`)
----
이전에 컴파운트 패턴을 적용한 컴포넌트들과 비슷하게 `chat-container/chat-bubble` 폴더 내부에 컴포넌트 파일과 `types`
파일들이 명시되어 있습니다. 
`types` 폴더에도 이전 구조와 비슷하게 `chatBubble.ts`에는 사용되는 atom들에 관한 타입을, `variantChatbubble.ts`에는 atom들로 구성된 3가지 variant 형태의 타입들을 명시해두고 있습니다.
```tsx
// chatBubbl.ts
export interface ChatBubbleContainerProps
extends React.HTMLAttributes<HTMLDivElement> {
variant: 'ME' | 'OPPONENT' | 'SYSTEM';
children: React.ReactNode;
}
...
---------------------------
// variantChatBubble.ts
interface CommonProps extends React.HTMLAttributes<HTMLDivElement> {
content: string;
time?: string;
}
export interface MeProps extends CommonProps {}
export interface OpponentProps extends CommonProps {
name: string; …
```
=> ✨ [Feat] 채팅 말풍선 컴포넌트 구현

src/app/chat/page.tsx, src/constants/navigation.ts, src/features/chat/components/chat-header/ChatHeader.tsx, src/features/chat/container/BookClubChatContainer.tsx, src/features/chat/container/ChatContainer.tsx, src/features/chat/container/ExchangeChatContainer.tsx, src/middleware.ts
=> 💄[Design] 채팅 페이지 UI 개발 #231

src/components/card/Card.stories.tsx, src/components/card/Card.tsx, src/components/card/types/card.ts, src/features/club-create/container/RadioButtonGroup.tsx
> ex) #190
> 기존 카드 컴포넌트에서 온라인일 경우 장소 정보 대신 아이콘과 '온라인' 텍스트를 띄워주도록 변경했습니다.
Card 컴포넌트의 atom인 `CardLocation` 을 수정했습니다. (props로 `meetingType`, `isPast` 추가로 받고 분기 처리)
온라인 
온라인 - 지난 모임
아마 크게 에러나는 부분은 없는 걸로 확인했는데 혹시 카드를 활용한 부분에서 에러가 나게되면 말씀해주세요!
=> ✨ [Feat] 카드 모임 '온라인' 인경우 장소대신 온라인 텍스트 추가

src/features/chat/components/chat-card/types/variantChatCard.ts, src/features/chat/container/BookClubChatContainer.tsx
> ex) #이슈번호, #이슈번호
> 이번 PR에서 작업한 내용을 간략히 설명해주세요
=> refactor: 취소된 모임 채팅 목록에서 삭제

src/app/chat/[id]/page.tsx, src/features/chat-room/container/chat-bubble-list/components/ChatMessage.tsx, src/features/chat/container/BookClubChatContainer.tsx
> ex) #이슈번호, #이슈번호
> 이번 PR에서 작업한 내용을 간략히 설명해주세요
=> refactor: 채팅방에서 상대 이미지 보이게

src/app/chat/[id]/page.tsx, src/features/chat-room/container/chat-bubble-list/components/ChatMessage.tsx, src/features/chat/components/chat-card/types/variantChatCard.ts, src/features/chat/container/BookClubChatContainer.tsx
> ex) #이슈번호, #이슈번호
> 이번 PR에서 작업한 내용을 간략히 설명해주세요
=> 채팅방 다른 유저 프로필 이미지 보이게 구현

README.md
=> 📝[Docs] 리드미 포맷 적용

src/features/chat-room/container/chat-bubble-list/ChatBubbleList.stories.tsx
> ex) #333 
> ChatBubbleLIst storybook 에러 수정
해당 컴포넌트에서 next router 기능을 사용하고 있지만, 스토리북은 Next 환경이 아니므로 발생하는 에러.
스토리북에 모의 라우터 적용
=> 🐛[Fix] ChatBubbleList storybook router 에러 fix

src/components/card/Card.tsx
> #323
- 모임 찾기 카드 호버 효과 적용
- 마이페이지 참여한 모임 카드, 리뷰 작성하기 호버 효과 적용, 참여 취소하기 버튼 색상 변경
- 마이페이지 만든 모임 카드 호버 효과 적용, 모임 취소하기 버튼 색상 변경
=> 💄[Design] 모임 카드, 버튼 호버 효과 적용
