codeit-team3/FE

src/components/text-chip/TextChip.stories.tsx, src/components/text-chip/TextChip.test.tsx, src/components/text-chip/TextChip.tsx
> ex) #18 , #19 
> 카드등에 확인되는 textChip 컴포넌트 개발 및 테스트
* 스토리북 크로매틱 주소 : https://6746699afaee05c7e6fef863-isfbdwkzsh.chromatic.com/?path=/story/components-textchip--default
* 기본값은 텍스트 흰색
* 마감 임박 여부 boolean값을 받아 텍스트 색상을 변경하도록 지정
> 카드리스트에서 보여질때 디자인상으로 마감 여부가 임박한 요소의 색이 주황색으로 변하는게 맞는건지 아님 시간을 그냥 주황색으로 한건지 헷갈리네요
=> ✨ [Feat] TextChip 컴포넌트 개발

public/icons/SearchIcon.tsx, src/components/search-box/SearchBox.stories.tsx, src/components/search-box/SearchBox.test.tsx, src/components/search-box/SearchBox.tsx
> #120
> 검색창 공용 컴포넌트 구현
현재는 피그마 디자인 모임 찾기 부분에서만 사용중이라 그 부분 참고해서 만들었습니다. 추후 다른 페이지에서 다른 디자인으로 적용 된다면 variant도 prop에 추가하겠습니다.
외에는 특별 사항 없고 평소 사용하시던 input 처럼 사용하시면 됩니다 😀
=> ✨[Feat] 검색창 구현 #120

src/components/button/Button.tsx, src/components/tab/Tab.test.tsx, src/components/tab/Tab.tsx, src/constants/button.ts
> #134 
> Sub_Tab 디자인이 변경 되어 수정했습니다.
=> 💄[Design] Sub_Tab 디자인 변경

src/components/header/HeaderBar.test.tsx, src/components/header/HeaderBar.tsx, src/features/auth/utils/cookies.ts
> #137 
> 토큰을 쿠키에 저장할 때 만료 시간도 함께 저장하여 만료 시간 이후에 자동으로 삭제 되게 수정했습니다. 
추가적으로 헤더 바에서 새로고침하면 isLoggedIn 상태를 업데이트 하여 현재 로그인 되어 있는지 확인 할 수 있습니다.
근데 새로고침을 해야만 로그인 상태가 풀리는 문제점이 있긴 합니다....
=> ♻️[Refactor] 토큰 만료 시간 추가, 헤더 바 새로고침 시 isLoggedIn 상태 확인 #137

src/app/layout.tsx, src/components/button/Button.stories.tsx, src/components/button/Button.tsx, src/constants/button.ts
> #11 #143
> 버튼 컴포넌트의 컬러 확장성을 위해 코드 리팩토링 하였습니다. 
**Solid**
```javascript
<Button text='확인' size='medium' fillType='solid' themeColor='green-normal-01'/>
```
**Outline**
```javascript
<Button text='확인' size='medium' fillType='outline' themeColor='green-normal-01'/>
```
**Light Solid**
```javascript
<Button text='확인' size='medium' fillType='lightSolid' themeColor='green-normal-01' lightColor='green-light-03'/>
```
**<변경사항>**
- fillType variant : 'solid', 'outline', 'lightSolid'
- themeColor
- 버튼 컬러의 가장 기본 컬러로, 필수 입력 prop입니다.
- fillType: solid => 폰트 컬러는 흰색이며 버튼의 배경컬러에 themeColor이 적용됩니다. 
- fillType: outline => 폰트 컬러와 보더 컬러에 themeColor가 적용되며 배경 컬러는 흰색이 됩니다.
- lightColor
- fillType: lightSolid일 때 배경색이 되는 컬러이며 선택 입력 prop입니다.
- fillType : lightSolid => 폰트 컬러에는 themeColor가 적용되고 버튼 배경 컬러에 …
=> ♻️[Refactor] 버튼 컴포넌트 리팩토링 #143

src/store/authStore.ts
> ex) #148 
> 토큰 시간 만료 시 유저 정보 초기화 추가하였습니다.
=> ♻️[Refactor] 토큰 만료 시 유저 정보 초기화 #148

src/app/layout.tsx, src/components/header/HeaderBar.tsx, src/components/written-review/WrittenReview.stories.tsx, src/components/written-review/club-review/ClubReview.stories.tsx, src/components/written-review/club-review/ClubReview.tsx
> #154
> WrittenReview를 활용한 ClubReview 컴포넌트 생성 
Compound Pattern으로 WrittenReview의 자식 컴포넌트를 사용하여 모임 상세페이지에서 사용되는 리뷰 컴포넌트를 생성했습니다.
```js
const exampleReview = {
ratingCount: 4,
comment: '아침부터 자기발전을 위한 시간을 가져서 좋았어요. 각자의 길 위에서 달려가는 생생한 순간을 공유해주셔서 감사합니다!',
userProfile: {
profileImage:
'https://cdn.pixabay.com/photo/2024/02/17/00/18/cat-8578562_1280.jpg',
userName: '다람쥐',
createdAt: '2024.01.25',
},
};
<ClubReview
ratingCount={exampleReview.ratingCount}
comment={exampleReview.comment}
userProfile={exampleReview.userProfile}
/>
```
#130 
이전에는 사용해야 하는 곳에서 자식 컴포넌트를 직접 조합해야 하기 때문에 간결하지 못하는 단점이 있었습니다.
이를 개선하고자 완성된 컴포넌트로 분리하였습니다.
@sunnwave 코드를 살펴보시겠다고 하셔서 모임 상세페이지에서 쓰이는 리뷰 컴포넌트만 따로 생성했습니다!
마이페이지에서 사용되는 리뷰 컴포넌트는 스토리북 `Mypage Review`에서 확인할 수 있습니다! (이 부분은 건들지 않아서 그대롭니다)
=> ✨[Feat] WrittenReview를 활용한 ClubReview 컴포넌트 생성 #154

src/components/header/HeaderBar.tsx, src/features/auth/container/login-form/LoginForm.tsx
> #176
- **로그인 상태 확인 위치:** Header Bar에서 `checkLoginStatus` 호출.
- **문제점:**
- [프로필 버튼]이 [로그인 버튼]으로 변경되려면 페이지 새로고침 해야 했음.
1. **엑세스 토큰 만료**:
- 브라우저 **쿠키에서 토큰 제거**.
2. **사용자가 토큰이 필요한 페이지 접근**:
- 예: 찜하기 페이지.
- **미들웨어**에서 토큰 유무 확인 후, 토큰이 없으면 **로그인 페이지로 리다이렉션**.
3. **로그인 페이지에서 로그인 상태 업데이트**:
- `checkLoginStatus` 호출.
- `isLoggedIn` 상태를 `false`로 변경.
4. **Header Bar 상태 업데이트**:
- `isLoggedIn` 상태 변화를 감지.
- [프로필 버튼] → [로그인 버튼]으로 변경.
- **페이지 새로고침 없이** [프로필 버튼]이 [로그인 버튼]으로 변경.
=> ♻️ [Refactor] checkLoginStatus를 로그인 페이지에서 확인 #176

src/components/rating-display/RatingDisplay.tsx, src/features/club-details/components/DescriptionSection.tsx, src/features/club-details/components/HeaderSection.tsx, src/features/club-details/components/ReviewList.tsx, src/features/club-details/components/ReviewSummary.tsx, src/features/club-details/types/index.ts, src/mocks/mockDatas.ts, src/types/bookclubs.ts
> #270
- 추가된 응답값 적용
- ratingCounts 적용하여 평점별 리뷰 개수 표시
- 모임 이미지
- 상세 정보에 마감 시간 및 전체 주소 추가
- 리뷰 작성일 날짜 변환
- 요청값 추가 시 수정되어야 하는 부분
- 주최자와 참여 여부에 따라 달라지는 버튼
- 주최자 닉네임 및 프로필 이미지
- 주최자 id로 주최자(타유저) 프로필로 이동
- 상세 정보에 전체 주소 추가
- 리뷰 작성자 닉네임 및 프로필 이미지
=> ✨[Feat] 모임 상세 평점별 리뷰 개수 구현

src/features/club-details/components/ReviewSummary.tsx, src/features/club-details/utils/rating.ts
> ex) #279
> 상세조회 페이지 리뷰 리스트 프로그레스바 수정
변경 전 (프로그레스바의 percentage에 카운트만 전달하는 상태)
변경 후 (percentage에 count/totalCount * 100) 식으로 전달
=> ♻️ [Refactor] 상세조회 페이지 리뷰 리스트 프로그레스바 수정 

src/api/book-club/react-query/customHooks.ts, src/features/club-create/container/DatePickerField.tsx, src/features/club-create/container/FormContainer.tsx, src/features/club-create/hooks/useBookClubForm.ts, src/features/club-create/types/bookClubSchema.ts
> ex) #280,
> 모집 마감 날짜 -> 만나는 날 이전으로만 선택 가능하도록 구현
모집 마감 날짜 -> 만나는 날 이전으로만 선택 가능
만약, 만나는 날을 20일 선택 -> 모집 마감 날짜를 20일 이전인 19일로 선택 -> 다시 만나는 날을 10일로 선택하면 여전히 모집 마감 날짜가 만나는 날 이후가 되게 됩니다.
이러한 경우는 제출시 스키마를 통해 검사합니다.
```tsx
.superRefine((data, ctx) => {
....
if (data.endDate && data.targetDate) {
if (data.endDate >= data.targetDate) {
ctx.addIssue({
code: z.ZodIssueCode.custom,
message: '모집 마감일은 모임 날짜보다 이전이어야 합니다',
path: ['endDate'],
});
}
}
});
```
=> ✨ [Feat] 모임 만들기 모집 마감 날짜 -> 만나는 날 이전으로만 선택 가능하도록 구현

src/app/chat/[id]/page.tsx, src/features/auth/api/auth.ts, src/features/auth/api/refreshAccessToken.ts, src/lib/utils/apiClient.ts, src/middleware.ts
> #245 #283
> 
- 채팅방에서 뒤로가기 버튼
- 채팅방 헤더 누르면 해당 모임 상세 페이지로 이동
- 채팅 입력폼 화면 하단에 고정
=> ♻️[Refactor] 채팅 리펙토링 #283

src/api/book-club/react-query/customHooks.ts, src/api/book-club/react-query/likeOptimisticUpdate.ts, src/components/common-layout/FilterBar.tsx, src/components/common-layout/FilterSection.tsx, src/features/bookclub/components/BookClubMainPage.tsx, src/features/bookclub/hooks/useFetchBookClubList.ts, src/features/club-details/components/ReviewSummary.tsx, src/features/club-wish/components/WishPage.tsx, src/lib/constants/filters.ts, src/types/bookclubs.ts
>#290 #291 #292
**모임 목록 조회 페이지**
- 신청 가능 필터 기존 로직 제거 및 api 사용
- 찜하기 딜레이 문제 확인 및 해결
- 문제: #291
- 해결: #292 
**모임 상세 페이지**
- 리뷰 평균이 NaN일 경우, 0으로 표시
- 주최자: 모임 취소하기 후 모임 목록 캐시 무효화
찜하기 클릭 시 UI 즉각 적용
https://github.com/user-attachments/assets/3894f0ca-2bfb-4be9-b382-8f13727e0174
**낙관적 업데이트**를 사용하여 찜하기 UI 딜레이 문제를 해결했어요!
찜하기 버튼을 클릭했을 때, 찜 상태가 즉시 반영되지 않고 두 번 클릭해야 상태가 반영됨.
1. 찜하기 요청 → 서버 데이터 변경 (시간 소요)
2. `invalidateQueries` 호출 → 캐시 무효화 → 서버에서 데이터 다시 가져옴 (추가 시간 소요)
3. UI가 새 데이터를 반영 (최종적으로 변경됨)
즉, 두 번 클릭이 필요했던 이유는 **`invalidateQueries`로 캐시를 무효화한 후 네트워크 요청이 완료되기까지 시간이 걸리기 때문**입니다.
1. 낙관적 업데이트를 적용하여 UI와 캐시가 먼저 업데이트하고, 네트워크 요청의 결과를 기다리지 않고 즉시 반영합니다.
2. `invalidateQueries`는 캐시 무효화를 초래하여 UI와 데이터 동기화에 텀을 유발하므로 제거합니다.
> 관련 상세 내용은 위의 해결 이슈를 참고해주세요!
찜하기를 클릭했을 때 UI가 바로 반영되고 있습니다만... 로직이 맞는지는 확신이 없네요...ㅎㅎ
낙관적 …
=> ✨[Feat] api 수정 및 추가 사항 적용

src/api/book-club/bookClubMainAPI.ts, src/api/book-club/react-query/customHooks.ts, src/api/book-club/react-query/likeOptimisticUpdate.ts
> ex) #289, #292
> 찜하기 버그 수정 (찜하기시 유저 프로필 페이지에 반영 안되는 문제)
현재 찜하기쪽에서 발생하는 버그가 크게 다음 2가지 입니다.
1. 찜하기, 찜해제가 2번씩 눌러야 동작함
2. 유저 프로필 페이지에서 찜하기 이후 새로고침해야 하트 반영됨
1번 내용은 @wynter24 님이 작성해주신 https://github.com/codeit-team3/FE/issues/292 이슈 확인하면 될 것 같습니다!
해당 이슈에서 낙관적 업데이트 처리를 해주고 있기 때문에 찜하기/찜해제 동작이 바로 반영이 될 수 있을 것 같습니다.
(조회 쿼리를 `state`로 관리하고 Props로 내려주고 있는 로직은 발표 이후 개선해보면 좋을 것 같습니다!)
2번은 해당 페이지에서 사용되는 쿼리가 찜하기/찜해제시 무효화되지 않고 있었습니다. 
**찜하기/찜해제시에는 bookclub관련 정보들이 전체적으로 많이 바뀌어야하기 때문에 bookclub 쿼리 전체를 무효화**하도록 수정했습니다.
수정 전에는 찜을 안한 상태에서 찜하기를 실행하면 계속 찜이되지않고 찜하기만 무한으로 반복되고 있었는데, 
수정 후 찜하기, 찜해제 모두 2번씩 누르면 동작하는 것 확인했습니다. (이 부분은 민경님이 작성해주신 pr과 합치면 같이 해결될 부분인 것 같습니다!)
@wynter24  https://github.com/codeit-team3/FE/pull/293 님이 올려주신 Pr 머지 후, 테스트해봤는데 추후에 수정작업이 필요합니다! 우선 해당 pr에서 filters 부분이 빠져야할 것 같습니다! (해당 필터를 가진 쿼리키만 …
=> 🐛 [Bug] 찜하기 동작 에러

src/api/auth/authClientAPI.ts, src/api/auth/react-query/customHooks.ts, src/api/book-club/bookClubMainAPI.ts, src/components/header/HeaderBar.tsx, src/constants/avatar.ts, src/features/chat-room/container/chat-bubble-list/components/ChatMessage.tsx, src/features/club-details/components/ReviewList.tsx, src/features/club-details/mocks/DetailReviewDatas.ts, src/features/profile/components/clubs/ProfileWrittenReview.tsx, src/features/profile/components/info/Info.tsx, src/features/profile/components/info/InfoEditModal.tsx, src/features/profile/container/MyJoinedClubList.tsx, src/features/profile/hooks/useEditInfo.tsx, src/features/profile/types/index.ts, src/features/profile/utils/infoEditFormUtils.tsx, src/mocks/mockDatas.ts, src/types/review.ts
> #287
> 마이페이지에서 프로필 이미지를 수정하는 기능 api 연동
- 프로필 이미지 수정 뒤에 다시 수정을 하면 바로 이미지 변경이 반영되지 않고 시간이 좀 흐른 뒤에 반영이 되는 것으로 보입니다. 이부분이 서버쪽의 문제인지 프론트쪽의 문제인지 파악이 필요할 것 같습니다 
- 리뷰에 대한 이미지 응답값이 변경된 부분이 있어서 모임 상세페이지의 리뷰 부분도 수정하였습니다 
- 현재는 채팅방에서 프로필 이미지 값이 제대로 입력이 안 되는 것 같아서  이 부분도 수정하면 좋을 것 같습니다.
- 로그아웃 시에도 토스트 알림이 있으면 좋을 것 같아서 추가해두었습니다
=> ✨[Feat] 프로필 이미지 수정하기 #287

src/app/chat/[id]/page.tsx
> #305
기존에는 채팅 내용이 많아지면 페이지 자체에 스크롤이 생겼었는데, 현재는 채팅이 보이는 컨테이너 부분만 스크롤이 생기는 것으로 수정
https://github.com/user-attachments/assets/e872e13a-f036-4f9e-abc1-307537cc5594
그냥  postition absolute을 줘버렸는데, 괜찮을까요? 해결은 된 거 같긴합니다.
=> ♻️[Refactor] 채팅창 높이 지정 #305

src/app/layout.tsx, src/components/header/HeaderBar.tsx, src/components/toast/toast.tsx, src/features/auth/api/auth.ts
> #309
로그아웃 시 토스트가 사라지지 않는 버그가 있었는데, 이유는 모르겠는데(충돌 해결하면서 들어갔나..) layout.tsx에 토스트 컴포넌트가 두번 들어가있었습니다.
하나 삭제하여 해결했습니다!
=> ♻️[Refactor] 토스트가 사라지지 않는 버그 수정

src/api/auth/react-query/customHooks.ts, src/api/book-club/react-query/customHooks.ts, src/constants/messages/toast.ts, src/features/club-details/hooks/useJoinClub.ts, src/features/profile/container/MyJoinedClubList.tsx, src/lib/hooks/useCancelClub.ts, src/lib/hooks/useLeaveClub.ts, src/lib/hooks/useLikeClub.ts, src/lib/hooks/useUnLikeClub.ts
> #312
토스트에서 사용되는 메시지들 한 파일에서 상수로 관리
토스트 메시지를 새로 추가하게 된다면 src > constants > messages > toasts.ts 에 추가하시면 됩니다
=> ♻️[Refactor] 토스트 메시지 상수로 관리

src/components/progress-bar/ProgressBar.test.tsx, src/components/progress-bar/ProgressBar.tsx
> ex) #310 
> 프로그레스바의 넘침 현상을 해결
프로그레스바에서 `percentage` 가 100이상으로 들어올 경우 처리를 해두긴했지만 애초에 이런 경우가 들어오지 않도록,
**프론트에서는 '정원 = 참여자 수' 일 경우 더 이상 참여를 못하도록,
백엔드에서도 이런 경우 요청이 오면 에러를 내도록** 추가 처리가 필요할 것 같습니다.
=> ♻️ [Refactor] 프로그레스바 넘침 현상 해결

src/features/auth/container/login-form/LoginForm.test.tsx
> #317
- 유효하지 않은 이메일 형식을 입력하면 에러 메시지 표시 되는 것에 대한 테스트 추가
- 초기 상태에서는 로그인 버튼 비활성화, 이메일과 비밀번호를 입력했을 때 로그인 버튼 활성화 테스트 추가
=> ✅[Test] 로그인 테스트 코드 추가

jest.config.js, src/features/club-create/container/FormContainer.tsx, src/features/club-create/container/ImageField/ImageField.test.tsx, src/features/club-create/container/ImageField/ImageField.tsx, src/features/club-create/container/RadioButtonGroup/RadioButtonGroup.test.tsx, src/features/club-create/container/RadioButtonGroup/RadioButtonGroup.tsx
> ex) #116 
>  모임 만들기 페이지 컴포넌트 일부 단위 테스트 작성
모임 만들기에서 사용되는 일부 컴포넌트들의 단위 테스트를 작성했습니다.
추가로 api쪽을 연결한 통합테스트나 cypress를 통한 e2e테스트의 경우 추후에 좀 더 알아보고 진행해야 할 것 같습니다.
`jest.config.js` 에 코드를 절대 경로 매핑을 할 수 있도록 코드를 추가했습니다
=> [Test] 모임 만들기 페이지 단위 테스트 코드 작성

src/features/bookclub/components/ClubListSection.tsx, src/features/club-details/components/HeaderSection.tsx, src/lib/hooks/useLikeWithAuthCheck.ts
> #336
- 모임 찾기 페이지에서 비 로그인 상태에서 찜 클릭 시 로그인 안내창 띄우기
찜하기 관련 오류 미해결에 대한 임시 방편으로 비 로그인 유저가 찜하기를 클릭했을 때 로그인 안내창을 띄우는 로직을 추가하였습니다.
=> ✨[Feat] 모임 찾기 페이지 비로그인 찜 클릭 시 로그인 안내창 추가 #336
